# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-18 18:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20201118_2137'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Editor',
        ),
    ]
